global:
  scrape_interval: 15s
  scrape_timeout: 1s
  evaluation_interval: 15s
scrape_configs:
  - job_name: dev-scrape
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["127.0.0.1:9885"]
        labels:
          service: "prom-scrape-fluentbit"
