service:
  flush: 1
  log_level: info

pipeline:
  inputs:
    - name: http
      port: 9881
      listen: 0.0.0.0
      successful_response_code: 200
      success_header:
        - x-fluent-bit received
        - x-fluent-bit-2 im_a_tea_pot
      tag: http

  outputs:
    - name: stdout
      match: "*"
