service:
  flush: 1
  log_level: debug

pipeline:
  inputs:
    - name: http
      port: 9882
      listen: 0.0.0.0
      successful_response_code: 200
      success_header: x-fluent-svc fluent-bit
      tls: on
      tls.crt_path: /etc/pki/tls/certs/fb-book
      tls.ca_file: /etc/pki/tls/certs/fb-book
      tag: http

  outputs:
    - name: stdout
      match: "*"
