service:
  flush: 1
  log_level: debug

pipeline:
  inputs:
    - name: http
      port: 9881
      listen: 0.0.0.0
      successful_response_code: 201
      success_header: x-fluent-bit received
      tag: http

  outputs:
    - name: forward
      match: "*"
      host: 0.0.0.0
      port: 9980
