env:
  flush_interval: 1

service:
  flush_interval: ${flush_interval}
  log_level: info

pipeline:
  inputs:
    - name: disk
      interval_sec: 5
      tag: book_vm_disk

    - name: cpu
      interval_sec: 5
      tag: book_vm_cpu

    - name: mem
      interval_sec: 5
      tag: book_vm_memory

    - name: netif
      interface: eth0
      interval_sec: 5
      tag: book_vm_network

  outputs:
    - name: stdout
      match: "*"
