service:
  flush_interval: 5
  log_level: info
  streams_file: ./create2.conf

pipeline:
  inputs:
    - name: random
      tag: random-num
      interval_sec: 1

  filters:
    - name: stdout
      match: "*"

  outputs:
    - name: stdout
      match: myStream.*
