service:
  flush_interval: 5
  log_level: info
  streams_file: ./query.conf

pipeline:
  inputs:
    - name: random
      interval_sec: 1
      tag: random-num
      alias: myRandom

    - name: random
      tag: random-num
      interval_sec: 1

  outputs:
    - name: null
      match: "*"
#   - name: stdout
#     match: "*"
#     json_date_format: iso8601
