env:
  flush_interval: 1

service:
  flush: ${flush_interval}
  log_level: info

pipeline:
  inputs:
    - name: dummy
      Dummy: '{ "hello": "my world" }'
      tag: dummy1

    #inputs:
    - name: dummy
      Dummy: '{ "more": "stuff" }'
      tag: dummy2

  outputs:
    - name: stdout
      match: "*"

    #outputs:
    - name: stdout
      match: "*"
      Format: json
      json_date_format: iso8601
