apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
data:
  fluent-bit.conf: |
    [SERVICE]
      flush 1

    [SOURCE]
      name tail
      tag source1
      path /var/log/1.log

    [SOURCE]
      name tail
      tag source2
      path /var/log/2.log

    [OUTPUT]
      name file
      match *
      file /var/combined-output.txt
      format plain
