global:
  scrape_interval: 15s
  scrape_timeout: 1s
  evaluation_interval: 15s
scrape_configs:
  - job_name: dev-scrape
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["<your host IP e.g. 192.168.0.205>:9885"]
        labels:
          service: "prom-scrape-fluentbit"
