service:
  flush: 1
  daemon: off
  log_level: info

pipeline:
  inputs:
    - name: dummy
      tag: dummy1
      dummy: '{   "time": "12/May/2023:08:05:52 +0000",   "remote_ip": "10.4.72.163",   "remoteuser": "-",   "request": {     "verb": "GET",     "path": " /downloads/product_2",     "protocol": "HTTP",     "version": "1.1"   },   "response": 304}'

    - name: dummy
      tag: dummy2
      dummy: '{   "time": "12/June/2023:08:05:52 +0000",   "remote_ip": "10.4.72.163",   "remote_user": "-",   "request": {     "verb": "GET",     "path": " /downloads/product_2",     "protocol": "HTTP",     "version": "1.1"   },   "response": 304, "another_root_element" : "horrah", "why" : ["just"," so", " the counter"," varies"]}'

    - name: fluentbit_metrics
      tag: fluentbitmetrics
      scrape_interval: 15
      scrape_on_start: true

  filters:
    - name: lua
      match: "*"
      call: cb_addElementCount
      script: ./attribute-count.lua
      protected_mode: true

  outputs:
    - name: stdout
      match: "*"
